repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb", "5000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: ["svg"]
      - id: trailing-whitespace
        exclude_types: ["svg"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--tab-width", "2", "--trailing-comma", "es5"]
        additional_dependencies: ["prettier", "prettier-plugin-astro"]
        exclude: "pnpm-lock.yaml"
