# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    # Specify the language and version your project requires,
    # by uncommenting one of the following tools.
    #
    # python: "3.13"
    # ruby: "3.3"
    nodejs: "22"
    # rust: "1.82"
    # golang: "1.23"

  commands:
    - npm install -g pnpm@latest-10
    - make install
    - make build PREVIEW=true
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cd dist && cp -r * $READTHEDOCS_OUTPUT/html
