services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "run", "dev", "--host", "0.0.0.0"]
    ports:
      - "4321:4321"
    environment:
      - ASTRO_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .pnpm-store:/app/.pnpm-store

volumes:
  node_modules:
