name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - ep2026
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timestamp for build/deploy
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: ssh keyscan
        run: ssh-keyscan "static.europython.eu" > ~/.ssh/known_hosts

      - name: Download data
        env:
          EP_SESSIONS_API: ${{ vars.EP_SESSIONS_API }}
          EP_SPEAKERS_API: ${{ vars.EP_SPEAKERS_API }}
          EP_SCHEDULE_API: ${{ vars.EP_SCHEDULE_API }}
        run: make download-data

      - name: Download avatars
        run: make download-avatars

      - name: Build and deploy
        run: make ship FORCE_DEPLOY=true
